### ISSUE TITLE
When I try to load dataset, there is an issue `AssertionError: There are no other images for mosaic augment` accured

### ISSUE THREAD

**Issue by scao0208** [yjwong1999/yolov8-multitask#1]
Hi,

I am trying to deploy and train your model. But when I try to load images with your code, the mistake shows that are at least two images are needed for the method `Mosaic`.

Could you help me to solve this problem?

Thank you,
Ashley

```bash
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    model.train(data='/home/siyu/Documents/yolov8-multitask/ultralytics/datasets/bdd-multi-toy.yaml', batch=4, epochs=10, imgsz=(640,640), name='v4_640', val=True, task='multi',classes=[0,1,2,3,4,5,6,7,8,9,10,11],combine_class=[0,1,2,3,4,5,6,7,8,9],single_cls=True)
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/engine/model.py", line 387, in train
    self.trainer.train()
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/engine/trainer.py", line 334, in _do_train
    for i, batch in pbar:
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/siyu/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/data/base.py", line 282, in __getitem__
    transfer = self.transforms(label_list)
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/data/augment.py", line 56, in __call__
    data = t(data)
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/data/augment.py", line 56, in __call__
    data = t(data)
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/data/augment.py", line 118, in __call__
    labels = self._mix_transform(labels)
  File "/home/siyu/Documents/yolov8-multitask/ultralytics/yolo/data/augment.py", line 192, in _mix_transform
    assert len(labels.get('mix_labels', [])), 'There are no other images for mosaic augment.'
AssertionError: There are no other images for mosaic augment.
```

**Comment by scao0208** [comment]
I found the Jiayuan's repository(https://github.com/JiayuanWang-JW/YOLOv8-multi-task) and it can work now.
